#!/bin/sh
# extracts initrd info from a [b]zImage file
# uses: binoffset (new), dd, zcat, strings, grep
# $arg1 is [b]zImage filename

binoffset="./binoffset"
test -e $binoffset || cc -o $binoffset ./binoffset.c || exit 1

GZHDR_BASE="0x1f 0x8b 0x08"

dump_initrd() {
    file="$1"

    echo "Dumping initrd.extracted ..."

    start=`$binoffset $file $GZHDR_BASE 2>/dev/null`
    [ "$?" != "0" ] && start="-1"
    if [ "$start" -eq "-1" ]; then
	return
    fi

    dd if="$file" ibs=1 skip="$start" 2>/dev/null | zcat > initrd.extracted

    echo "done."

    clean_up
    exit 0
}


usage()
{
	echo "  usage: extract-initrd [b]zImage_filename"
}

clean_up()
{
	if [ "$TMPFILE" != "" ]; then
		rm -f $TMPFILE
	fi
}

if [ $# -lt 1 ]
then
	usage
	exit 1
fi

GZHDR1="0x1f 0x8b 0x08 0x00"
GZHDR2="0x1f 0x8b 0x08 0x08"

TMPFILE=`mktemp -t kernel-XXXXXX` || exit 1
image="$1"

# vmlinux: Attempt to dump the configuration from the file directly

off=`$binoffset "$image" $GZHDR1 2>/dev/null`
[ "$?" != "0" ] && off="-1"
if [ "$off" -eq "-1" ]; then
	off=`$binoffset "$image" $GZHDR2 2>/dev/null`
	[ "$?" != "0" ] && off="-1"
fi
if [ "$off" -eq "0" ]; then
	zcat <"$image" >"$TMPFILE"
	dump_initrd "$TMPFILE"
elif [ "$off" -ne "-1" ]; then
	(dd ibs="$off" skip=1 count=0 && dd bs=512k) <"$image" 2>/dev/null | \
		zcat >"$TMPFILE"
	dump_initrd "$TMPFILE"
fi


echo "ERROR: Unable to extract kernel configuration information."
echo "       This kernel image may not have the config info."

clean_up
exit 1
